using System;

namespace Euler
{
    class Program
    {
        static void Main(string[] args)
        {
            string threeToFive = Mult3_5(1000);
            Console.WriteLine(threeToFive);
            Console.WriteLine(EvenFib(4000000));
        }

        static public string Mult3_5(int limit)
        {
            /*  PROBLEM DESCRIPTION
            If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
            Find the sum of all the multiples of 3 or 5 below 1000.
            */
            int sum = 0;
            for (int i = 3; i < limit; i++)
            {
                if (i % 3 == 0 || i % 5 == 0)
                { sum += i; }
            }
            return $"The sum of all multiples of 3 and 5 less than {limit} is {sum}.";
        }

        static public string EvenFib(int limit)
        {
            /* PROBLEM DESCRIPTION
                Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

                By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            */

            int sum = 0;
            int fib1 = 1;
            int fib2 = 1;

            while (fib2 < limit)
            {
                if (fib2 % 2 == 0)
                {
                    sum += fib2;
                }
                int tempFib = fib1;
                fib1 = fib2;
                fib2 = fib2 + tempFib;
            }

            return $"The sum of all even fibonnacci numbers less than {limit} is {sum}.";
        }
    }
}

